spring:
  application:
    name: GATEWAY-SERVER
  # profile:
  #   active: dev
  cloud:
    config:
      name: gateway-server
      uri: http://configuration-server:8888
  config:      
   import: "optional:configserver:"

