spring:
  application:
    name: GATEWAY-SERVER
  # profile:
  #   active: dev
  cloud:
    config:
      name: gateway-server
      uri: http://configuration-server:8888
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
  config:      
   import: "optional:configserver:"


